### ISSUE TITLE
翰哥,😂😂😂能不能升级成JSONModel的swift版?支持model嵌套不?

### ISSUE THREAD

**Issue by zdiovo** [johnlui/JSONNeverDie#3]
翰哥,
如果有swift版本的JSONModel替代库告诉我下吧.😂
没有的话,能不能升级成JSONModel的swift版?

**Comment by johnlui** [comment]
原来是叫 JSONModel。。。我搜了一下还没搜到。。。。
兼容 JSONModel 还是不要了。。。。

**Comment by zdiovo** [comment]
抱歉啊,写错了JSONModel,我想知道model嵌套model支持不?我测试了一下,好像不可以.

**Comment by johnlui** [comment]
必须支持呀：https://github.com/johnlui/JSONNeverDie/wiki#3-something-you-need-to-know

**Comment by zdiovo** [comment]
😜请原谅我没仔细看文档
看了下,感觉还是要手动解决数组里面嵌入model的问题啊😂
有没有自动级联的方案,像MJExtension那样.

**Comment by johnlui** [comment]
你可以贡献一下代码哦~~
