### ISSUE TITLE
个人觉得在处理JSON转Model的时候，由Model提供一个Map更好一些

### ISSUE THREAD

**Issue by tailang** [johnlui/JSONNeverDie#4]
Hello,johnlui:
JSONNeverDie在处理JSON转Model的时候，是通过Mirror映射获得对象的属性，然后通过属性名的获取JSON中对应的数据，赋值给对象。这样的话属性名和JSON必须一一对应。假设出现下面的情况付出的代价就比较大：  

```
//一开始服务端提供的数据格式
{“string”: "json", "float": 1.0, "int": 1}
```

``` swift
class TestModel: JSONNDModel {
    var string = ""
    var float: Float = 0.0
    var int = 0
}
```

这样处理没什么问题，然后在n各文件中调用了m次 

``` swift
let testModel = TestModel((JSONNDObject: json)
testModel.string
testModel.float
testModel.int
```

突然有一天服务端因为需求的变化，不得不将string的字段换成char，那我必须修改成

``` swift
class TestModel: JSONNDModel {
    var char = ""
    var float: Float = 0.0
    var int = 0
}
```

并且要将项目中所有的`testModel.string`换成`testModel.char`，这样付出的代价比较大了。

所以我觉得可以让Mode提供一个l可选Map，用于映射，如果有Map按照Map映射处理。没有提供Map则按照Mirror的方式映射

**Comment by johnlui** [comment]
丢弃 map 是进步之一呀。。。。
而且修改成员变量之后，所有问题编译器都会自动报错编译不过的，甚至通过一些简单的 @available (*, unavailable, renamed="RAWValue") 可以做到自动提示，双击自动变为新的。

**Comment by johnlui** [comment]
感谢你的反馈！

对了，忘了说了，JSONNeverDie 也是可以手动 map 的，你看嵌套就是靠手动实现的。。。。

**Comment by tailang** [comment]
哦哦，原来还可以这样干... thx
